---
- hosts: proxmox_all_lxc
  become: yes
  tasks:
    - name: update apt packages
      apt:
          upgrade: 'yes'
          update_cache: yes
- hosts: proxmox_nodes
  become: yes
  tasks:
    - name: update apt packages
      apt:
          upgrade: 'yes'
          update_cache: yes
